global:
  scrape_interval: 5s

scrape_configs:

  - job_name: "api-services"
    static_configs:
      - targets:
          - host.docker.internal:3001
          - host.docker.internal:3002
          - host.docker.internal:3003

  - job_name: "pgbouncer"
    static_configs:
      - targets:
          - host.docker.internal:9127

  - job_name: "postgres"
    static_configs:
      - targets:
          - host.docker.internal:9187

  - job_name: "redis"
    static_configs:
      - targets:
          - host.docker.internal:9121
